spring.application.name=ZapSender

zapsender.verify.token=${ZAPSENDER_VERIFY_TOKEN}
zapsender.access.token=${ZAPSENDER_ACCESS_TOKEN}
zapsender.phone.number.id=${ZAPSENDER_PHONE_NUMBER_ID}
zapsender.api.url=https://graph.facebook.com/v24.0/${ZAPSENDER_PHONE_NUMBER_ID}/messages
