@startuml

autonumber

title UC10 - Consultar Extrato

actor Professor as P
actor Aluno as A

participant "Tela do Sistema" as Tela
participant "ControleTransacao" as CT

database "PostgreSQL\nTransacoes" as DBTransacao

group Consulta realizada pelo Professor

P -> Tela : consultarExtrato(professorID)
activate Tela

Tela -> CT : solicitarExtrato(professorID)
activate CT

CT -> DBTransacao : buscarTransacoes(professorID)
activate DBTransacao

DBTransacao --> CT : listaTransacoes
deactivate DBTransacao

alt Transações encontradas
    CT --> Tela : extratoGerado(listaTransacoes)
    Tela --> P : exibirExtrato()
else Nenhuma transação encontrada
    CT --> Tela : listaNaoEncontrada()
    Tela --> P : exibirMensagemVazia()
end

deactivate CT
deactivate Tela

end

group Consulta realizada pelo Aluno

A -> Tela : consultarExtrato(alunoID)
activate Tela

Tela -> CT : solicitarExtrato(alunoID)
activate CT

CT -> DBTransacao : buscarTransacoes(alunoID)
activate DBTransacao

DBTransacao --> CT : listaTransacoes
deactivate DBTransacao

alt Transações encontradas
    CT --> Tela : extratoGerado(listaTransacoes)
    Tela --> A : exibirExtrato()
else Nenhuma transação encontrada
    CT --> Tela : listaNaoEncontrada()
    Tela --> A : exibirMensagemVazia()
end

deactivate CT
deactivate Tela

end

@enduml